env:
  browser: true
  es2021: true
  node: true
root: true
parser: '@typescript-eslint/parser'
extends:
  - plugin:@typescript-eslint/recommended
  - prettier
plugins:
  - '@typescript-eslint'
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  no-unused-vars: 'off'
  consistent-return: 'off'
  '@typescript-eslint/no-unused-vars':
    - error
ignorePatterns:
  - .github
  - .nyc_output
  - .vscode
  - coverage
  - dist
  - node_modules
